//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sql_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Choice
    {
        public int Q_Id { get; set; }
        public string choice1 { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
